# Generated by Django 5.0.1 on 2024-01-16 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0003_alter_tbl_fueltype_fueltype_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_fueltype',
        ),
    ]
