# Generated by Django 5.0.1 on 2024-01-16 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0004_delete_tbl_fueltype'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_fueltype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fueltype_name', models.CharField(max_length=20)),
            ],
        ),
    ]
