# Generated by Django 5.0.1 on 2024-01-17 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0006_tbl_place'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_fuelrate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuelrate_name', models.CharField(max_length=20)),
                ('fueltype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_fueltype')),
            ],
        ),
    ]
