# Generated by Django 5.0.1 on 2024-01-20 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0007_tbl_fuelrate'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_towingvehicletype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(max_length=20)),
            ],
        ),
    ]
