# Generated by Django 4.2.7 on 2024-01-23 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin', '0010_tbl_admin'),
        ('Guest', '0005_tbl_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_vehicledetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_details', models.CharField(max_length=100)),
                ('vehicle_image', models.FileField(upload_to='vehicle/')),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_dealer')),
                ('vtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_towingvehicletype')),
            ],
        ),
    ]
