# Generated by Django 4.2.7 on 2024-01-23 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0005_tbl_user'),
        ('TowingAgent', '0002_rename_dealer_tbl_vehicledetails_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_vehicledetails',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_towingagent'),
        ),
    ]
