# Generated by Django 5.0.1 on 2024-01-20 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin', '0009_tbl_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dealer_name', models.CharField(max_length=20)),
                ('dealer_email', models.CharField(max_length=30)),
                ('dealer_contact', models.CharField(max_length=15)),
                ('dealer_address', models.CharField(max_length=50)),
                ('dealer_password', models.CharField(max_length=20)),
                ('dealer_photo', models.FileField(upload_to='DealerDoc/')),
                ('dealer_proof', models.FileField(upload_to='DealerDoc/')),
                ('dealer_vstatus', models.CharField(default=0, max_length=5)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_place')),
            ],
        ),
    ]
