# Generated by Django 5.0.1 on 2024-01-20 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0009_tbl_location'),
        ('Guest', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dealer',
            new_name='tbl_dealer',
        ),
    ]
