# Generated by Django 5.0.1 on 2024-01-20 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0009_tbl_location'),
        ('Guest', '0002_rename_dealer_tbl_dealer'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_towingagent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_name', models.CharField(max_length=20)),
                ('agent_email', models.CharField(max_length=30)),
                ('agent_contact', models.CharField(max_length=15)),
                ('agent_address', models.CharField(max_length=50)),
                ('agent_password', models.CharField(max_length=20)),
                ('agent_photo', models.FileField(upload_to='DealerDoc/')),
                ('agent_proof', models.FileField(upload_to='DealerDoc/')),
                ('agent_vstatus', models.CharField(default=0, max_length=5)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_place')),
            ],
        ),
    ]
