# Generated by Django 4.2.7 on 2024-01-23 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Guest', '0005_tbl_user'),
        ('Admin', '0010_tbl_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_fuelbooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fbooking_date', models.DateField(auto_now_add=True)),
                ('fbooking_status', models.CharField(default=0, max_length=5)),
                ('fbooking_amount', models.IntegerField(default=0, max_length=50)),
                ('fbooking_address', models.CharField(max_length=100)),
                ('payment_status', models.CharField(default=0, max_length=10)),
                ('fbooking_qty', models.IntegerField(default=0, max_length=50)),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_dealer')),
                ('fueltype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_fueltype')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_location')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user')),
            ],
        ),
    ]
